"""
quality_score.py

Data Quality Scoring module for Agentic BI Analyst.

Responsibilities:
- Calculate overall data quality score
- Calculate column-level quality scores
- Evaluate missing values
- Evaluate uniqueness
- Evaluate outliers
- Evaluate constant / near-constant columns
- Identify quality issues
- Generate quality summary

This module DOES NOT modify the input DataFrame.
"""

from typing import Any, Dict, List
import pandas as pd


class QualityScoreProfiler:
    """
    Calculates data quality scores using metadata
    and statistical profiling results.
    """

    def __init__(
        self,
        df: pd.DataFrame,
        metadata_profile: Dict[str, Any],
        statistics_profile: Dict[str, Any]
    ):
        """
        Initialize quality scoring profiler.

        Parameters
        ----------
        df:
            Original pandas DataFrame.

        metadata_profile:
            Output generated by metadata.py.

        statistics_profile:
            Output generated by statistics.py.
        """

        if not isinstance(df, pd.DataFrame):
            raise TypeError(
                "QualityScoreProfiler requires a pandas DataFrame."
            )

        if not isinstance(metadata_profile, dict):
            raise TypeError(
                "metadata_profile must be a dictionary."
            )

        if not isinstance(statistics_profile, dict):
            raise TypeError(
                "statistics_profile must be a dictionary."
            )

        self.df = df
        self.metadata = metadata_profile
        self.statistics = statistics_profile

    # =========================================================
    # MISSING VALUE SCORE
    # =========================================================

    def missing_value_score(
        self,
        column: str
    ) -> float:
        """
        Calculate quality score based on missing values.

        100 = no missing values
        0   = completely missing
        """

        missing_data = self.statistics.get(
            "missing_values",
            {}
        ).get(column)

        if not missing_data:
            return 100.0

        missing_percentage = float(
            missing_data.get(
                "missing_percentage",
                0
            )
        )

        score = 100.0 - missing_percentage

        return round(
            max(0.0, min(100.0, score)),
            2
        )

    # =========================================================
    # UNIQUENESS SCORE
    # =========================================================

    def uniqueness_score(
        self,
        column: str
    ) -> float:
        """
        Calculate uniqueness quality score.

        This is primarily useful for identifying columns
        that are expected to contain unique values.

        For general columns, the score is informational.
        """

        unique_data = self.statistics.get(
            "unique_values",
            {}
        ).get(column)

        if not unique_data:
            return 100.0

        uniqueness = float(
            unique_data.get(
                "uniqueness_percentage",
                0
            )
        )

        return round(
            max(0.0, min(100.0, uniqueness)),
            2
        )

    # =========================================================
    # OUTLIER SCORE
    # =========================================================

    def outlier_score(
        self,
        column: str
    ) -> float:
        """
        Calculate quality score based on outlier percentage.

        100 = no outliers
        Lower score = more outliers
        """

        outlier_data = self.statistics.get(
            "outliers",
            {}
        ).get(column)

        if not outlier_data:
            return 100.0

        outlier_percentage = float(
            outlier_data.get(
                "outlier_percentage",
                0
            )
        )

        score = 100.0 - outlier_percentage

        return round(
            max(0.0, min(100.0, score)),
            2
        )

    # =========================================================
    # CONSTANT / NEAR-CONSTANT SCORE
    # =========================================================

    def variation_score(
        self,
        column: str
    ) -> float:
        """
        Detect constant and near-constant columns.

        Constant columns receive 0.
        Near-constant columns receive 50.
        Normal columns receive 100.
        """

        constant_data = self.statistics.get(
            "constant_columns",
            {}
        ).get(column)

        if not constant_data:
            return 100.0

        if bool(
            constant_data.get(
                "is_constant",
                False
            )
        ):
            return 0.0

        if bool(
            constant_data.get(
                "is_near_constant",
                False
            )
        ):
            return 50.0

        return 100.0

    # =========================================================
    # COLUMN QUALITY SCORE
    # =========================================================

    def column_quality_score(
        self,
        column: str
    ) -> Dict[str, Any]:
        """
        Calculate complete quality score for one column.
        """

        missing_score = self.missing_value_score(
            column
        )

        uniqueness_score = self.uniqueness_score(
            column
        )

        outlier_score = self.outlier_score(
            column
        )

        variation_score = self.variation_score(
            column
        )

        # -----------------------------------------------------
        # Determine column type
        # -----------------------------------------------------

        numeric_columns = set(
            self.df.select_dtypes(
                include="number"
            ).columns
        )

        is_numeric = column in numeric_columns

        # -----------------------------------------------------
        # Calculate weighted score
        # -----------------------------------------------------

        if is_numeric:

            # Numerical columns:
            # Missing values = 35%
            # Outliers = 30%
            # Variation = 20%
            # Uniqueness = 15%

            score = (
                missing_score * 0.35
                + outlier_score * 0.30
                + variation_score * 0.20
                + uniqueness_score * 0.15
            )

        else:

            # Categorical columns:
            # Missing values = 40%
            # Variation = 35%
            # Uniqueness = 25%

            score = (
                missing_score * 0.40
                + variation_score * 0.35
                + uniqueness_score * 0.25
            )

        score = round(
            max(0.0, min(100.0, score)),
            2
        )

        # -----------------------------------------------------
        # Quality classification
        # -----------------------------------------------------

        if score >= 90:
            quality_level = "Excellent"

        elif score >= 75:
            quality_level = "Good"

        elif score >= 60:
            quality_level = "Fair"

        elif score >= 40:
            quality_level = "Poor"

        else:
            quality_level = "Critical"

        # -----------------------------------------------------
        # Detect issues
        # -----------------------------------------------------

        issues: List[str] = []

        if missing_score < 100:
            issues.append(
                "Missing values detected"
            )

        if outlier_score < 100:
            issues.append(
                "Potential outliers detected"
            )

        if variation_score == 0:
            issues.append(
                "Constant column"
            )

        elif variation_score == 50:
            issues.append(
                "Near-constant column"
            )

        return {
            "quality_score": score,
            "quality_level": quality_level,
            "missing_value_score": missing_score,
            "uniqueness_score": uniqueness_score,
            "outlier_score": outlier_score,
            "variation_score": variation_score,
            "issues": issues
        }

    # =========================================================
    # ALL COLUMN QUALITY SCORES
    # =========================================================

    def column_scores(
        self
    ) -> Dict[str, Dict[str, Any]]:
        """
        Calculate quality scores for every column.
        """

        results = {}

        for column in self.df.columns:

            results[column] = (
                self.column_quality_score(column)
            )

        return results

    # =========================================================
    # OVERALL QUALITY SCORE
    # =========================================================

    def overall_quality_score(
        self
    ) -> float:
        """
        Calculate overall dataset quality score.

        The score is the average of all column
        quality scores.
        """

        scores = self.column_scores()

        if not scores:
            return 100.0

        values = [
            float(result["quality_score"])
            for result in scores.values()
        ]

        score = sum(values) / len(values)

        return round(
            max(0.0, min(100.0, score)),
            2
        )

    # =========================================================
    # QUALITY LEVEL
    # =========================================================

    def quality_level(
        self,
        score: float
    ) -> str:
        """
        Convert numerical quality score into
        a human-readable quality level.
        """

        if score >= 90:
            return "Excellent"

        elif score >= 75:
            return "Good"

        elif score >= 60:
            return "Fair"

        elif score >= 40:
            return "Poor"

        return "Critical"

    # =========================================================
    # QUALITY ISSUES
    # =========================================================

    def quality_issues(
        self
    ) -> List[Dict[str, Any]]:
        """
        Generate a list of detected data quality issues.
        """

        issues = []

        scores = self.column_scores()

        for column, result in scores.items():

            for issue in result["issues"]:

                issues.append({
                    "column": column,
                    "issue": issue,
                    "quality_score": result[
                        "quality_score"
                    ],
                    "severity": result[
                        "quality_level"
                    ]
                })

        return issues

    # =========================================================
    # QUALITY SUMMARY
    # =========================================================

    def summary(self) -> Dict[str, Any]:
        """
        Generate high-level quality summary.
        """

        overall_score = (
            self.overall_quality_score()
        )

        column_results = (
            self.column_scores()
        )

        issues = self.quality_issues()

        excellent_columns = 0
        good_columns = 0
        fair_columns = 0
        poor_columns = 0
        critical_columns = 0

        for result in column_results.values():

            level = result["quality_level"]

            if level == "Excellent":
                excellent_columns += 1

            elif level == "Good":
                good_columns += 1

            elif level == "Fair":
                fair_columns += 1

            elif level == "Poor":
                poor_columns += 1

            elif level == "Critical":
                critical_columns += 1

        return {
            "overall_quality_score": overall_score,

            "overall_quality_level": (
                self.quality_level(
                    overall_score
                )
            ),

            "total_columns": int(
                len(self.df.columns)
            ),

            "total_rows": int(
                len(self.df)
            ),

            "columns_excellent": (
                excellent_columns
            ),

            "columns_good": (
                good_columns
            ),

            "columns_fair": (
                fair_columns
            ),

            "columns_poor": (
                poor_columns
            ),

            "columns_critical": (
                critical_columns
            ),

            "total_quality_issues": int(
                len(issues)
            )
        }

    # =========================================================
    # COMPLETE QUALITY PROFILE
    # =========================================================

    def profile(self) -> Dict[str, Any]:
        """
        Generate complete data quality profile.
        """

        overall_score = (
            self.overall_quality_score()
        )

        return {
            "overall_quality_score": (
                overall_score
            ),

            "overall_quality_level": (
                self.quality_level(
                    overall_score
                )
            ),

            "column_scores": (
                self.column_scores()
            ),

            "quality_issues": (
                self.quality_issues()
            ),

            "summary": (
                self.summary()
            )
        }


# =============================================================
# CONVENIENCE FUNCTION
# =============================================================

def calculate_quality_score(
    df: pd.DataFrame,
    metadata_profile: Dict[str, Any],
    statistics_profile: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Convenience function for calculating
    data quality scores.

    Example:

        quality = calculate_quality_score(
            df,
            metadata,
            statistics
        )
    """

    profiler = QualityScoreProfiler(
        df=df,
        metadata_profile=metadata_profile,
        statistics_profile=statistics_profile
    )

    return profiler.profile()


